### ISSUE TITLE
訂購端＿完成送餐關懷日誌，只能在訂單追蹤區看得到，在我的長輩專區看不到

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/lib#1]
如題
![IMG_6142](https://user-images.githubusercontent.com/99379113/154902649-512762ca-ffb5-4fc6-875b-8294f0c76408.PNG)
![IMG_6143](https://user-images.githubusercontent.com/99379113/154902682-795ec751-14a5-492d-915d-462d8cc598b4.PNG)
![IMG_6145](https://user-images.githubusercontent.com/99379113/154902683-22463e45-8bf9-43a0-9fbd-9d38c51ae68e.PNG)

**Comment by chunyenHuang** [comment]
已修正
![Simulator Screen Shot - iPhone 12 Pro - 2022-02-21 at 19 42 04](https://user-images.githubusercontent.com/12788155/155059097-919e2dbe-ed85-425a-977c-00068295ffae.png)
