### ISSUE TITLE
首頁被台灣大哥大基金會建議，不要放入購物車選單，應改為其他

### ISSUE THREAD

**Issue by silvergate2022** [silver-gate/lib#3]

**Comment by chunyenHuang** [comment]
所以要拿掉 生鮮飲食和綠燈龍專區嗎？
![Simulator Screen Shot - iPhone 12 Pro - 2022-02-21 at 19 44 25](https://user-images.githubusercontent.com/12788155/155059290-d87981c8-7748-4709-8ac0-9d321d62a079.png)
